//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssistanceOnlineDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssistanceUsers
    {
        public int Id_course { get; set; }
        public System.DateTime Assistance_date { get; set; }
        public string Id_user { get; set; }
    
        public virtual AssistanceCourses AssistanceCourses { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual UsersCourses UsersCourses { get; set; }
    }
}
