//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssistanceOnlineDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AssistanceOnlineContext : DbContext
    {
        public AssistanceOnlineContext()
            : base("name=AssistanceOnlineContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HtmlTemplate> HtmlTemplate { get; set; }
        public virtual DbSet<Key> Key { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<AssistanceCourses> AssistanceCourses { get; set; }
        public virtual DbSet<AssistanceUsers> AssistanceUsers { get; set; }
        public virtual DbSet<UsersCourses> UsersCourses { get; set; }
        public virtual DbSet<Courses> Courses { get; set; }
    
        public virtual int Sp_InsertCourse(string id_user, string name, string description, string password)
        {
            var id_userParameter = id_user != null ?
                new ObjectParameter("Id_user", id_user) :
                new ObjectParameter("Id_user", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_InsertCourse", id_userParameter, nameParameter, descriptionParameter, passwordParameter);
        }
    }
}
